name: CI con gradle

on:
  push:
   branches: [master]
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
    contents: read
    packages: write
   
   steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: set up gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 2.1
      
    - name: hacer build del frontend
      working-directory: src/Clients
      run: ./gradlew build
      
    - name: hacer build del backend
      working-directory: src/Backend/OrderService
      run: ./gradlew build test
      
    - name: dockerizar el front y el backend
      run: |
        cp src/Clients/build/libs/*.war deploy/docker/clients/drop #copiar el resultado del build para la nueva imagen
        docker build -t p2gps/web deploy/docker/clients
         cp src/Backend/OrderService/build/libs/ordering* deploy/docker/order/drop
         docker build -t p2gps/order deploy/docker/Order
   
   

